#!/bin/sh
#
# @name octocopter3 SITL
#
# @type Octocopter H
#
# @maintainer KL
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 14

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 8
param set-default CA_ROTOR0_PX 1.08     #v1.13.0 버전에서 toml 파일의 position X값  # Position of rotor 0 along X body axis relative to center of gravity
param set-default CA_ROTOR0_PY 0.543    #v1.13.0 버전에서 toml 파일의 position y값 #Position of rotor 0 along Y body axis relative to center of gravity
param set-default CA_ROTOR0_KM -0.004432417    # Cq / Moment coefficient of rotor 0 /  The moment coefficient if defined as " Torque = KM * Thrust ". Use a positive value for a rotor with CCW rotation. Use a negative value for a rotor with CW rotation./ -일경우 CW로 회전 / [-1, 1] /default 0.05
# param set-default CA_ROTOR0_CT 0.068596678   # Ct / Thrust coefficient of rotor / The thrust coefficient if defined as  " Thrust = CT * u^2 ", where u (with value between actuator minimum and maximum) is the output signal sent to the motor controller / default 6.5
#param set-default CA_ROTOR0_AZ   # Axis of rotor 0 thrust vector, Z body axis component / Only the direction is considered (the vector is normalized). / [-100, 100] / default -1.0 / 로터가 드론의 몸체 Z축을 따라 힘을 가하는 방향을 의미
#param set-default mot_kv    #motor velocity or motor speed constant / Motor Kv(motor velocity constant) in RPM per volt / Comment: Motor Kv in RPM per volt. This can be taken from the motor’s specification sheet; accuracy will help control performance but some deviation from the specified value is acceptable. / [0, 4000] / default 2300 / rpm per volt
# Cm    #Non-dimensional drag torque coefficient.  This relates to the axial torque produced by a spinning propeller.
# Cm  = 0.05
#<maxRotVelocity>4000</maxRotVelocity>    # Ω or Max Rotational Velocity = Kv * Max Applied Voltage * Max Motor Efficiency * 2π / 60
#<motorConstant>8.54858e-05</motorConstant>  # Motor Constant = Thrust / (Ω) ²
#<momentConstant>0.06</momentConstant>  #Moment Constant = 60 / (2π * Kv)
param set-default CA_ROTOR1_PX -1.08
param set-default CA_ROTOR1_PY -0.543
param set-default CA_ROTOR1_KM -0.004432417
# param set-default CA_ROTOR1_CT 0.068596678

param set-default CA_ROTOR2_PX 0.36
param set-default CA_ROTOR2_PY 0.543
param set-default CA_ROTOR2_KM 0.004432417     #v1.13.0 버전에서 toml 파일의 CM값 , +일경우 CCW로 회전
# param set-default CA_ROTOR2_CT 0.068596678

param set-default CA_ROTOR3_PX -1.08
param set-default CA_ROTOR3_PY 0.543
param set-default CA_ROTOR3_KM 0.004432417
# param set-default CA_ROTOR3_CT 0.068596678

param set-default CA_ROTOR4_PX 1.08
param set-default CA_ROTOR4_PY -0.543
param set-default CA_ROTOR4_KM 0.004432417
# param set-default CA_ROTOR4_CT 0.068596678

param set-default CA_ROTOR5_PX -0.36
param set-default CA_ROTOR5_PY -0.543
param set-default CA_ROTOR5_KM 0.004432417
# param set-default CA_ROTOR5_CT 0.068596678

param set-default CA_ROTOR6_PX 0.36
param set-default CA_ROTOR6_PY -0.543
param set-default CA_ROTOR6_KM -0.004432417
# param set-default CA_ROTOR6_CT 0.068596678

param set-default CA_ROTOR7_PX -0.36
param set-default CA_ROTOR7_PY 0.543
param set-default CA_ROTOR7_KM -0.004432417
# param set-default CA_ROTOR7_CT 0.068596678

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108



# # disable attitude failure detection
# param set-default FD_FAIL_P 0
# param set-default FD_FAIL_R 0




